### ISSUE TITLE
Dataset description publication service

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/dataset-register#144]
Should there be a light-weight publication service? 
How to implement and manage such a service?

[Design document](https://docs.google.com/document/d/1RXyX6R1ChiyxCwrIJwdPPDq9u22wFwuks1X4woNloSk/) in progress

**Comment by ddeboer** [comment]
Experimented a bit, and registering https://raw.githubusercontent.com/ddeboer/test-conneg/main/dataset.jsonld locally works fine. It will also work in production as long as we allow the domain https://raw.githubusercontent.com. Is that acceptable @coret?

**Comment by coret** [comment]
So no content-negotiation troubles? Great!

I guess allowing dataset descriptions from raw.githubusercontent.com is opening the doors quite a bit. Maybe restrict to specific paths from this domain? Or not and "ditch" possible non-relevant datasets in the KG.

**Comment by ddeboer** [comment]
https://github.com/netwerk-digitaal-erfgoed/dataset-register-entries is now available, so we can probably close this issue.
