### ISSUE TITLE
Support Hydra pagination

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/dataset-register#151]
As seen for instance on https://opendata.picturae.com/catalog.ttl.

May also be relevant for Nationaal Archief.

Or support N-Quad Streaming? 

Each page must be complete in itself, for example have an Organization and its properties for the publisher predicate.

**Comment by ddeboer** [comment]
Comunica already seems to support this:

```
comunica-sparql 'https://opendata.picturae.com/catalog.ttl?page=1' 'select * { ?s ?p ?o} '
[
...
]
```

returns all datasets, including those from following pages.

**Comment by coret** [comment]
Picturae (or rather CKAN) has implemented hydra.
Hub3 (NA+CollectieNederland) will implement hydra.

**Comment by ddeboer** [comment]
@coret Do you have the URL for one or more paginated Hub3 collections? That way I can test at least two providers.

**Comment by ddeboer** [comment]
This is currently blocked by https://github.com/comunica/comunica/issues/1180.
