### ISSUE TITLE
Try to enforce HTTP IRIs in SHACL

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/dataset-register#161]
It seems SHACL only knows `sh:IRI`, which allows URNs, but let’s see if there’s a way to make the check more strict.

https://github.com/netwerk-digitaal-erfgoed/requirements-datasets/pull/44

**Comment by ddeboer** [comment]
We could use `dash:stem` or `sh:pattern: "^https?://"` but that would exclude relative IRIs from being used. Is that a problem?

**Comment by coret** [comment]
Have yet to see a dataset description with base IRI + relative IRIs. 

But, can't we just add 2 `sh:pattern`'s (via `sh:or`), one for absolute and one for relative? (maybe add a check for a base in the relative case)

**Comment by ddeboer** [comment]
A pattern for relative IRIs (e.g. `^/`) would not exclude URNs.

**Comment by ddeboer** [comment]
Discussed with @coret and decided to start with absolute `^https?://` for now.
