### ISSUE TITLE
Validation of multi-lingual properties

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/dataset-register#242]
Follow-up on issue https://github.com/netwerk-digitaal-erfgoed/requirements-datasets/issues/47 

Current requirements don't say anything about multi-lang properties, but it's a common feature of RDF. So dataset descriptions could contain multi-lang properties, see for example the dataset description [test datasetdescription 2i](https://demo.netwerkdigitaalerfgoed.nl/datasets/kb/2i.html) which contains:

```
"description": [
    {
      "@value": ""Alba amicorum van de Koninklijke Bibliotheek, een dataset gedefinieerd voor het Europeana Rise of Literacy project.",
      "@language": "nl"
    },
    {
      "@value": "Alba amicorum from the Koninklijke Bibliotheek, a dataset defined for the Europeana Rise of Literacy project.",
      "@language": "en"
    }
],
```

When you validate this dataset description, there are violations, this is caused by SHACL lines like:

https://github.com/netwerk-digitaal-erfgoed/dataset-register/blob/250e68cd3171a99bdc9e4472d5e7020c4b64416c/shacl/register.ttl#L114

and 

https://github.com/netwerk-digitaal-erfgoed/dataset-register/blob/250e68cd3171a99bdc9e4472d5e7020c4b64416c/shacl/register.ttl#L115

multilingual properties can't have a MaxCount and can't be a string. Suggestion is to remove these lines from the SHACL.

**Comment by ddeboer** [comment]
I will add a multilingual description to our automated tests and see how our query will handle that.

**Comment by coret** [comment]
Even one language specifier makes the count go above 1!

So with SHACL

```
reg:SchemaDescriptionProperty a sh:PropertyShape ;
    sh:path schema:description ;
    sh:minCount 0 ;
    sh:maxCount 1 ;
```

the validation of `schema:description     "Datadump Titels DBNL" ;` is ok, but `schema:description     "Datadump Titels DBNL"@nl ;` is not ok!

**Comment by coret** [comment]
Multilingual description/name added to test in https://github.com/netwerk-digitaal-erfgoed/dataset-register/pull/281
