### ISSUE TITLE
Missing creator with NOB datasets

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/dataset-register#262]
It seems the NOB data, like [example](https://data.spinque.com/ld/data/netwerkoorlogsbronnen/beeldbank_zaanstad/), is missing the **dct:creator** in the translated DCAT data in our triplestore ([example](https://triplestore.netwerkdigitaalerfgoed.nl/resource?uri=https:%2F%2Fdata.spinque.com%2Fld%2Fdata%2Fnetwerkoorlogsbronnen%2Fbeeldbank_zaanstad%2F&role=context)) - the data is present in the source, so something is wrong with our [code](https://github.com/netwerk-digitaal-erfgoed/dataset-register/blob/main/src/query.ts).

Curiously, transformed data from VGW (same IT supplier) does included dct:create (see [example](https://data.spinque.com/ld/data/vangoghworldwide/noord_brabants_museum/)).

**Comment by coret** [comment]
Additionally, the Spinque datasetdescriptions seem to miss a publisher and only have a creator (I will notify Spinque). I would have expected our crawler to spot the invalid datasetdescription and provide a signal.

**Comment by ddeboer** [comment]
The registered URL is https://data.spinque.com/ld/data/netwerkoorlogsbronnen/, which does not contain a creator (nor a publisher) for https://data.spinque.com/ld/data/netwerkoorlogsbronnen/beeldbank_zaanstad/. 

For backwards compatibility when changing our requirements, our SPARQL query has optionals for both creator and publisher. Because of this, the datasets at at https://data.spinque.com/ld/data/netwerkoorlogsbronnen/ are still found and processed.

**Comment by coret** [comment]
The example is was referencing is https://data.spinque.com/ld/data/netwerkoorlogsbronnen/beeldbank_zaanstad/ which does have a creator which I don't see in https://triplestore.netwerkdigitaalerfgoed.nl/resource?uri=https:%2F%2Fdata.spinque.com%2Fld%2Fdata%2Fnetwerkoorlogsbronnen%2Fbeeldbank_zaanstad%2F&role=context

**Comment by ddeboer** [comment]
> The registered URL is https://data.spinque.com/ld/data/netwerkoorlogsbronnen/, which does not contain a creator (nor a publisher) for https://data.spinque.com/ld/data/netwerkoorlogsbronnen/beeldbank_zaanstad/.

**Comment by coret** [comment]
The catalog is missing creator/publisher (separate datasets do contain do contain creator - to be changed in publisher).
Action: report issue to Spinque
