### ISSUE TITLE
Missing keywords in translated version

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/dataset-register#263]
Some datasets (like [example](https://www.openarch.nl/datasets/ghn)) include keywords in the description. These keywords are "lost in translation" due to the wrong selection of the property, starting in: https://github.com/netwerk-digitaal-erfgoed/dataset-register/blob/148d86234f92ab57a689395c021883178e4eb863/src/query.ts#L19

The [DCAT property](https://www.w3.org/TR/vocab-dcat-2/#Property:resource_keyword) is keyword, but the [schema.org property](https://schema.org/keywords) is keyword**s**

**Comment by ddeboer** [comment]
The actual line in question is https://github.com/netwerk-digitaal-erfgoed/dataset-register/blob/148d86234f92ab57a689395c021883178e4eb863/src/query.ts#L140
