### ISSUE TITLE
Validation should be "scoped" to the dataset

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/dataset-register#265]
When a organization adds meta-data about its organisation to its webpages, as suggested by Google via https://developers.google.com/search/blog/2013/05/using-schemaorg-markup-for-organization, and datasetdescriptions are published inline on the page too, our validation complains about the organization not having an IRI (as introduced in Require HTTP IRIs for dataset and publisher - https://github.com/netwerk-digitaal-erfgoed/dataset-register/pull/241).

[Example](https://haagsgemeentearchief.nl/): 
```
  {
	"@context": "http://schema.org",
	"@graph":
	  [
		{
		  "@type": "Organization",
		  "url": "https://haagsgemeentearchief.nl/",
		  "name": "Haags Gemeentearchief",
		  "logo": "https://haagsgemeentearchief.nl/templates/haagsebeeldbank/img/haagsebeeldbank.png",
		  "address": {
			"@type": "PostalAddress",
			"streetAddress": "Spui 70",
			"addressLocality": "Stadhuis",
			"postalCode": "2511 BT Den Haag",
			"addressCountry": "NL"
		  },
		  "contactPoint": [
			{ "@type": "ContactPoint",
			"telephone": "(070) 353 70 13",
			"contactType": "customer service"
		  }
		],
		"sameAs": [
		  "https://www.facebook.com/haagsgemeentearchief/"
		]
	  },
	  ....
	]
  }
```

[Another example](https://www.genealogieonline.nl/wo2slachtoffers/) (microdata):
```
<div temscope itemtype="http://schema.org/Organization">
<link itemprop="url" href="https://genealogie.coret.org/">
<p><a href="https://www.genealogieonline.nl/houmeopdehoogte.php">Uw nieuwsbrieven</a></p>
<p><a itemprop="sameAs" href="https://www.twitter.com/genealogie">Twitter</a></p>
<p><a itemprop="sameAs" href="https://www.facebook.com/genealogie.coret.org">Facebook</a></p>
<meta itemprop="logo" content="https://static.coret.org/img/cg/logo400x400-nl.png">
<meta itemprop="name" content="Coret Genealogie">
</div>
```

By providing an `@id` (in JSON-LD) or`itemid` (in microdata) to the organization, the data validates. But this should not be necessary, validation should only take into account the organizations referenced in the dataset(s).

**Comment by ddeboer** [comment]
Can you try to put this into SHACL?

**Comment by coret** [comment]
To test:
? remove all or Organization targetClass 
? schema:path of inversePath
? SPAQRL
