### ISSUE TITLE
Not all datasets from datacatalog processed

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/dataset-register#279]
From https://github.com/netwerk-digitaal-erfgoed/dataset-register/issues/252#issuecomment-931401148

> > the datasetdescriptions which are already in the Dataset Register aren't updated because no datasets are found
> 
> How did you reach that conclusion? [This query](https://triplestore.netwerkdigitaalerfgoed.nl/sparql?name=Recent%20geregistreerde%20URL%E2%80%99s&infer=true&sameAs=true&query=PREFIX%20schema%3A%20%3Chttp%3A%2F%2Fschema.org%2F%3E%0ASELECT%20%3Fstatus%20%3FdateRead%20FROM%0A%3Chttps%3A%2F%2Fdemo.netwerkdigitaalerfgoed.nl%2Fregistry%2Fregistrations%3E%0AWHERE%20%7B%20%0A%3Chttps%3A%2F%2Fwww.openarch.nl%2Fdatasets%2F%3E%20a%20schema%3AEntryPoint%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AdateRead%20%3FdateRead%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3Astatus%20%3Fstatus%20%0A%7D) shows us that the registration URL is valid and was read last night.
> 
> [This query](https://triplestore.netwerkdigitaalerfgoed.nl/sparql?name=Datasets%20met%20een%20linked%20data%20distributie&infer=true&sameAs=true&query=PREFIX%20dcat%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Fdcat%23%3E%0APREFIX%20dct%3A%20%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0A%0A%23%20Datasets%20met%20een%20linked%20data%20distributie%20(query%20op%20bij%20linked%20data%20gebruikte%20formats)%0A%0ASELECT%20%20%3Fformat%20WHERE%20%7B%0A%20%20%3Chttps%3A%2F%2Fwww.openarch.nl%2Fid%2Fdataset_bhi%3E%20dcat%3Adistribution%20%3Fdistribution%20.%0A%20%20%3Fdistribution%20dct%3Aformat%20%3Fformat%20.%0A%7D) seems to show the expected encoding formats.

Upon closer examination, it seems that some datasets were updated but some - like dataset_wba (see [query 1](https://triplestore.netwerkdigitaalerfgoed.nl/resource?uri=https:%2F%2Fwww.openarch.nl%2Fid%2Fdataset_wba)) - were **not** updated.

In the triplestore there are 36 datasets in the datacatalog Open Archives Data Catalog (see [query 2](https://triplestore.netwerkdigitaalerfgoed.nl/sparql?name=&infer=true&sameAs=true&query=PREFIX%20schema%3A%20%3Chttp%3A%2F%2Fschema.org%2F%3E%0Aselect%20*%20where%20%7B%20%0A%09%3Chttps%3A%2F%2Fwww.openarch.nl%2Fdatasets%2F%3E%09schema%3Aabout%20%3Fo%0A%7D)). That's 46 short, as the following query shows 82 datasets at the source:

```
comunica-sparql https://www.openarch.nl/datasets/ "SELECT * WHERE { ?s <http://schema.org/dataset> ?o . }"
[
{"?s":"https://www.openarch.nl/id/datacatalog","?o":"https://www.openarch.nl/id/dataset_ade"},
{"?s":"https://www.openarch.nl/id/datacatalog","?o":"https://www.openarch.nl/id/dataset_bhi"},
{"?s":"https://www.openarch.nl/id/datacatalog","?o":"https://www.openarch.nl/id/dataset_elo"},
...
{"?s":"https://www.openarch.nl/id/datacatalog","?o":"https://www.openarch.nl/id/dataset_wba"},
....
]
```

The https://www.openarch.nl/id/dataset_wba is one of the datasets missing in query 2, which is why this dataset wasn't updated.

Additionaly, I guess our crawler doesn't yet remove datasets graphs from our triplestore when they are no longer present in a datacatalog they were introduced by?

**Comment by ddeboer** [comment]
> Additionaly, I guess our crawler doesn't yet remove datasets graphs from our triplestore when they are no longer present in a datacatalog they were introduced by?

**Comment by coret** [comment]
> How many triples are on https://www.openarch.nl/datasets/?
```
 $ comunica-sparql https://www.openarch.nl/datasets/ "SELECT * WHERE { ?s ?p ?o . }" | wc -l
15660
```
Is this maximum of 10.000 triples based on best-practice or metrics? 

> We can of course raise that limit, but that comes at the cost of CPU and memory usage. And what if catalogs grow even further, both in breadth (number of datasets) and depth (amount of data per dataset)?

I guess we can learn from https://www.openarch.nl/datasets/ to see what the cost is. I previously generated a datacatalog of all customers of De Ree which was much larger. So I certainly feel we must be ready for growth. And not fail silently.

**Comment by ddeboer** [comment]
> Is it possible to do some sort of count of triples or datasets and issue a warning in API and crawler if this count exceeds our limit or is 0?

While we cannot know for sure how many triples our query would return if it were unlimited, we _can_ know if the SPARQL result size matches our limit. This indicates that we have to raise the limit further (or is pure coincidence, but this is rather unlikely). Because this is valuable information, I log this in #353.
