### ISSUE TITLE
KB datasets can not be validated or registered

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/dataset-register#291]
Currently there is only KB dataset in the registery (rise-alba). Adding new datasets based on the available dataset descriptions like http://data.bibliotheken.nl/id/dataset/persons fails. In the web interface shows "De URL kan worden gevonden, maar bevat geen datasets." but no helpful information is provided. Note that KB uses the 303 redirect (see Also) that points to the doc representation. Either the 'id' or 'doc' URI fails the test.

**Comment by ddeboer** [comment]
Closing this, as this issue cannot be fixed here.
