### ISSUE TITLE
Validating invalid Turtle shows a HTTP 502 error

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/dataset-register#310]
When you try to validate an invalid Turtle file (for example https://lab.coret.org/register/kb-dates-invalid.ttl which has a ; on line 16 which should be a .) our API responds with a HTTP 502 error ([link](https://datasetregister.netwerkdigitaalerfgoed.nl/validate.php?url=https%3A%2F%2Flab.coret.org%2Fregister%2Fkb-dates-invalid.ttl)).

```
shacl validate --shapes https://datasetregister.netwerkdigitaalerfgoed.nl/api/shacl --data https://lab.coret.org/register/kb-dates-invalid.ttl
18:57:11 ERROR riot            :: [line: 18, col: 3 ] Keyword 'a' not legal at this point
Loading data file
org.apache.jena.riot.RiotException: [line: 18, col: 3 ] Keyword 'a' not legal at this point
...
```

To do: it would be nice if our API would catch invalid syntax and provide a meaningfull return code (in the 4xx range as it a client error, not a server error). Otherwise, append 502 to our API documentation and describe invalid input as possible cause.

**Comment by ddeboer** [comment]
Fixed in Comunica, so we’re returning a proper 406 in this case now.
