### ISSUE TITLE
Only first dataset of datacatalog processed

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/dataset-register#332]
The datacatalog https://data.collectienederland.nl/doc/datacatalog consists of 3031 triples (JSON-LD) and describes 189 datasets and is [valid](https://datasetregister.netwerkdigitaalerfgoed.nl/validate.php?url=https%3A%2F%2Fdata.collectienederland.nl%2Fdoc%2Fdatacatalog).

After the URI of the datacatalog was registered, only [1 dataset](https://triplestore.netwerkdigitaalerfgoed.nl/sparql?name=&infer=true&sameAs=true&query=SELECT%20%3Fs%20WHERE%0A%7B%0A%20%20%20%20%3Fs%20%3Fp%20%3Fo%0A%20%20%20%20FILTER%20CONTAINS(str(%3Fs)%2C%22data.collectienederland.nl%2Fid%2Fdataset%22)%0A%7D%20GROUP%20BY%20%3Fs) was added to the Dataset Register.

I do not see any [non-200 status code in the registrations graph](https://triplestore.netwerkdigitaalerfgoed.nl/sparql?name=Crawl%20registrations%20not%20OK&infer=true&sameAs=true&query=PREFIX%20schema%3A%20%3Chttp%3A%2F%2Fschema.org%2F%3E%0APREFIX%20xsd%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F2001%2FXMLSchema%23%3E%0ASELECT%20*%20FROM%20%3Chttps%3A%2F%2Fdemo.netwerkdigitaalerfgoed.nl%2Fregistry%2Fregistrations%3E%0AWHERE%20%7B%20%0A%09%3Furl%20a%20schema%3AEntryPoint%20%3B%0A%09%20%20schema%3AdatePosted%20%3Fposted%20%3B%0A%20%20%20%20%20%20schema%3AdateRead%20%3Fread%20%3B%0A%20%20%20%20%20%20schema%3Astatus%20%3Fstatus%20%0A%20%20%20%20FILTER%20(str(%3Fstatus)%20!%3D%20%22200%22)%0A%7D) nor do I see any errors in the log.

As the datacatalog validates and the number of triples is below 10000, I think the issue is different than https://github.com/netwerk-digitaal-erfgoed/dataset-register/issues/279

**Comment by ddeboer** [comment]
The container crashes with OOM, so it seems to be the same cause as #279.

**Comment by ddeboer** [comment]
Verified this fix: all datasets from the URL are now [being crawled correctly](https://triplestore.netwerkdigitaalerfgoed.nl/sparql?name=Crawler&infer=true&sameAs=true&query=PREFIX%20schema%3A%20%3Chttp%3A%2F%2Fschema.org%2F%3E%0A%0ASELECT%20%3Fdataset%20(max(%3Fread)%20as%20%3FlastRead)%20%3Fregistration%20%3Fregistration_lastRead%20%3Fregistration_status%0AFROM%20%3Chttps%3A%2F%2Fdemo.netwerkdigitaalerfgoed.nl%2Fregistry%2Fregistrations%3E%0AWHERE%20%7B%20%0A%20%20%20%20%3Fdataset%20a%20schema%3ADataset%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AdateRead%20%3Fread%0A%20%20%20%20OPTIONAL%20%7B%20%3Chttps%3A%2F%2Fdata.collectienederland.nl%2Fdoc%2Fdatacatalog%3E%20schema%3Aabout%20%3Fdataset%20%3B%20%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3AdateRead%20%3Fregistration_lastRead%20%3B%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20schema%3Astatus%20%3Fregistration_status%20.%20%7D%0A%7D%0AGROUP%20BY%20%3Fdataset%20%3Fregistration%20%3Fregistration_lastRead%20%3Fregistration_status%0AORDER%20BY%20DESC(%3FlastRead)).
