### ISSUE TITLE
SPARQLAskValidator doesn't work with file (only sparql endpoint)

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/dataset-register#365]
To check the encodingFormat of a distribution against the IANA list, a first attempt was to use `sh:in` ( loooong list ):
https://github.com/netwerk-digitaal-erfgoed/dataset-register/blob/c232570a63af17d18a8de2398a1e66c5a4c675db/shacl/register.ttl#L153

A better approach (maintenance wise) would be to query a IANA list in RDF in combination with a SHACL `SPARQLAskValidator` (ASK, 
 because with a SELECT you can not test for absense). The  following data and SHACL shows attempts to use this method which can be locally tested with `shacl validate --shapes test.shacl.ttl --data test.data.ttl --debug`

Contents of `test.data.ttl`:
```
@prefix ex: <http://example.com/#> .

ex:aValidFormat a ex:Format1, ex:Format2;
	ex:hasEncodingFormat "text/turtle" .
  
ex:anInvalidFormat a ex:Format1, ex:Format2 ;
	ex:hasEncodingFormat "application/turtle" .
```

Contents of `test.shacl.ttl`:
```
@prefix ex:   <http://example.com/#> .
@prefix owl:  <http://www.w3.org/2002/07/owl#> .
@prefix rdf:  <http://www.w3.org/1999/02/22-rdf-syntax-ns#> .
@prefix rdfs: <http://www.w3.org/2000/01/rdf-schema#> .
@prefix sh:   <http://www.w3.org/ns/shacl#> .
@prefix xsd:  <http://www.w3.org/2001/XMLSchema#> .

ex:FormatShape
  a sh:NodeShape ;
  sh:targetClass ex:Format1 ;
  sh:property [
    sh:path ex:hasEncodingFormat ;
    ex:format "iana" ;	# howto use constraint without parameter??
    sh:severity sh:Warning ;
  ]
.

ex:FormatConstraintComponent
  a sh:ConstraintComponent ;
  sh:parameter [ sh:path ex:format ; ] ;
  sh:validator ex:inEncodingFormatList2 ;
.

ex:inEncodingFormatList1
	a sh:SPARQLAskValidator ;
	rdfs:comment "SPARQL query on Wikidata - note this list is incomplete" ;
	sh:message "A format from IANA list should be used"@en ;

	sh:ask """
		ASK {
			SELECT * { 
				SERVICE <http://query.wikidata.org/bigdata/namespace/wdq/sparql> { 
					?s <http://www.wikidata.org/prop/direct/P1163> $value
				} 
			} 
		}
    """
.

ex:inEncodingFormatList2
	a sh:SPARQLAskValidator ;
	sh:message "A format from IANA list should be used"@en ;

	sh:ask """
		ASK FROM <https://www.iana.org/assignments/media-types/> {
			SELECT * {
				SERVICE <https://triplestore.netwerkdigitaalerfgoed.nl/repositories/registry> { 
					?s <https://www.iana.org/hasMediaType> $value
				} 
			} 
		}
    """
.

ex:inEncodingFormatList3
	a sh:SPARQLAskValidator ;
	rdfs:comment "SPARQL query on a online file - seems not to work" ;
	sh:message "A format from IANA list should be used"@en ;

	sh:ask """
		ASK FROM <https://lab.coret.org/lod/DistributionEncodingFormats.ttl> { 
			?s <https://iana.org/hasMediaType> $value .
		}
    """
.

ex:inEncodingFormatList4
	a sh:SPARQLAskValidator ;
	rdfs:comment "SPARQL query on a local file - seems not to work - would probably be desired in terms of performance" ;
	sh:message "A format from IANA list should be used"@en ;

	sh:ask """
		ASK FROM <./DistributionEncodingFormats.ttl> { 
			?s <https://iana.org/hasMediaType> $value .
		}
    """
.
```	

By changing the `sh:validator` value in `ex:FormatConstraintComponent` you can use `ex:inEncodingFormatList1`, `ex:inEncodingFormatList2` ,`ex:inEncodingFormatList3` or `ex:inEncodingFormatList4`.

- Problem with `ex:inEncodingFormatList1` is that the list on Wikidata is imcomplete.
- For` ex:inEncodingFormatList2` the IANA list was stored in our triplestore. As can be seen by testing this method works, albeit not fast...
- `ex:inEncodingFormatList3` and `ex:inEncodingFormatList4` try to do the same query on a file (online or local). A local file might be preffered for performance. But neither of the validator seem to work....

**Comment by mightymax** [comment]
I do not believe using a RDF file (local or served over http/https) will work in your case when using a SHACL SPARQL based constraint, the Apache Jena `shacl` CLI tool can not build a Jena model in the CLI tool based on local files. This will rely heavily on the SHACL validator and how it implemented SPARQL in its engine. When using SPARQL as a remote access protocol over http, a proper SPARQL endpoint should exists, this can not be a file. 

You did not mention in this issue how you actually validate the RDF data using SHACL. Obviously you would not want to use the CLI in an automated or hosted workflow, but build a proper (Java based) pipeline. With that, your approach should work fine with local files, just build your Jena model from your RDF data and do the validation using the ASK query you already use.

When you do want to use the local file approach for the dataset RDF, or you want to provide simple tooling for creators of datasets, the federated ASK query is simply the best solution possible. If your (NDE) triple store is tool slow for your needs, upgrading that to a faster SPARQL endpoint is obviously a good approach. So your `ex:inEncodingFormatList2` is IMHO the best solution. For maintainability this is also nice, adding or removing supported media types is easy.

I did refactor your SHACL RDF a bit, for readability and simplicity. It also adds two extra constraints: cardinality and datatype.

```turtle
@prefix ex:   <http://example.com/#> .
@prefix sh:   <http://www.w3.org/ns/shacl#> .

ex:FormatShape
  a sh:NodeShape ;
  sh:targetClass ex:Format1 ;
  sh:property [
    sh:minCount 1;
    sh:maxCount 1;
    sh:path ex:hasEncodingFormat ;
    sh:datatype <http://www.w3.org/2001/XMLSchema#string> ;
    sh:severity sh:Warning ;
  	sh:sparql [
  		sh:select """
      ASK FROM <https://www.iana.org/assignments/media-types/> {
      			SELECT * {
      				SERVICE <https://triplestore.netwerkdigitaalerfgoed.nl/repositories/registry> { 
      					?s <https://www.iana.org/hasMediaType> $value
      				} 
      			} 
      		}
  			""" ;
  	]
  ]
.
```

**Comment by mightymax** [comment]
On a side note: you also mentioned that not all mediatypes that are defined in IANA registry are defined as a [P1163](http://www.wikidata.org/prop/direct/P1163) property. This is the case for 1.586 mediatypes! On the other hand, Wikidata has 645 mediatypes that are not defined in the IANA registry. Oddly enough, this also includes a widely used one: [image/gif](https://www.wikidata.org/wiki/Q2192)

* [Mediatypes from Wikidata not in IANA registry](https://github.com/netwerk-digitaal-erfgoed/dataset-register/files/7661087/mediatypes-not-in-IANA.txt)
* [Mediatypes from IANA registry not in Wikidata](https://github.com/netwerk-digitaal-erfgoed/dataset-register/files/7661093/mediatypes-not-in-wikidata.txt)

**Comment by coret** [comment]
https://github.com/zazuko/rdf-validate-shacl/ 

> rdf-validate-shacl does not support SHACL-SPARQL constraints

So, opting for the sh:in solution.
