### ISSUE TITLE
Only one schema:description allowed?

### ISSUE THREAD

**Issue by sdevalk** [netwerk-digitaal-erfgoed/dataset-register#397]
I'm trying to validate a (not yet published) dataset description from RKD. This description used to be valid, but now the SHACL validation returns a `Violation`.

The relevant part of the description looks like this:

```
<https://data.rkd.nl/thesaurus>
    a schema:Dataset ;
    schema:name "Thesaurus"@en, "Thesaurus"@nl ;
    schema:description "Description"@en, "Beschrijving"@nl .
```

The `resultMessage`: `"Moet precies één beschrijving hebben van type string of langString"@nl , "Must have a single description of type string or langString"@en ;`

This suggests that only one `schema:description` is allowed, whereas RKD wants to use (at least) two, one for each supported language. Is this a bug or a deliberate change?

**Comment by coret** [comment]
We thought we had fixed this issue with https://github.com/netwerk-digitaal-erfgoed/dataset-register/pull/304 but upon re-eaxmination of our SHACL there still is a MaxCount too many.
