### ISSUE TITLE
Validator can't find datasets in .json

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/dataset-register#558]
Validating a .json file with datasets results in a HTTP 406 (The URL can be resolved but it contains no datasets.)
Solition: rename the file to .jsonld, now the validator will find the dataset(s).

Cause?
Nicer solution: document, adjust error?

**Comment by ddeboer** [comment]
This is caused by a Content-Type of `application/json` instead of `application/ld+json` being returned. Nothing to be done here, in my opinion: JSON is not JSON-LD.
