### ISSUE TITLE
Datasetregister sparql endpoint doesn't allow remote construct queries

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/dataset-register#623]
Running a remote construct query on the datasetregister sparql endpoints results in a 405 error (not allowed). See example query on https://api.triplydb.com/s/StVKdSZV8. Why are remote construct queries not allowed?

**Comment by coret** [comment]
The SPARQL-endpoint of the Dataset Register is [https://triplestore.netwerkdigitaalerfgoed.nl/repositories/registry](https://triplestore.netwerkdigitaalerfgoed.nl/repositories/registry) (not https://triplestore.netwerkdigitaalerfgoed.nl/sparql).

**Comment by EnnoMeijers** [comment]
Thanks, just found that out ;) Closing this issue because I was using the wrong endpoint. Maybe we should communicate the right endpoint url (https://triplestore.netwerkdigitaalerfgoed.nl/repositories/registry) more clearly in the documentation or was I sleeping?

**Comment by coret** [comment]
The endpoint wasn't documented that promiment, you could have found it in the Data Stories.
In fact, a page specifically for developers who want to find heritage datasets was missing altogether. This has now been fixed: https://datasetregister.netwerkdigitaalerfgoed.nl/faq-developers.php?lang=en

**Comment by EnnoMeijers** [comment]
Great, thank you! Actually I did find it in the datastory ;)
