### ISSUE TITLE
Is openapi documentation hardcoded to https://datasetregister.netwerkdigitaalerfgoed.nl/api ?

### ISSUE THREAD

**Issue by mielvds** [netwerk-digitaal-erfgoed/dataset-register#666]
I ran my own instance of the datasetregister using a Docker build from the repository, which I tried accessing using a OpenAPI client (https://www.npmjs.com/package/swagger-client). This sort of works, but it's sending requests to the wrong API because my local OpenAI `http://localhost:3000/json` outputs https://datasetregister.netwerkdigitaalerfgoed.nl/api as the serverUrl instead of my local instance (e.g., `http://localhost:3000/api`). Can you configure this somehow?

**Comment by ddeboer** [comment]
Thanks for reporting! You can now select a local server in the API docs.

**Comment by mielvds** [comment]
Thanks @ddeboer. Minor thing: this works as long as you use port 3000. If I use a port mapping in docker, the port understandably does not use the external port. Can you configure your baseUrl manually somehow? Or are there ways to rewrite the port?

**Comment by ddeboer** [comment]
Could you just map `3000:3000`? That way it should still work.
