### ISSUE TITLE
create statistics for reporting

### ISSUE THREAD

**Issue by EnnoMeijers** [netwerk-digitaal-erfgoed/dataset-register#709]
In order to be able to report over the use of the Datasetregister logging of statics is necessary. The report should be able to show the number of queries, number of organisations and datasets. A periodical report will be required for reporting back to the board and the ministry.

**Comment by ddeboer** [comment]
B&G has expressed interest in statistics that show whether their datasets are being used. Is there a way for us to know this? Users downloading/querying distributions is really up to the dataset publishers to keep track of.

**Comment by coret** [comment]
I don't think we can see usage. We could track when a demonstrator user click on a distribution, but this won't give a complete picture. It won't see the usage by machines (they don't click links...).

As each datasetdescription has a kind of "landing" page (like [example](https://datasetregister.netwerkdigitaalerfgoed.nl/show.php?uri=https%3A%2F%2Fwww.openarch.nl%2Fid%2Fdataset_nba)), this could be counted/reported as well.

Another metric which might be of interest to datasetproviders is how many times their dataset occured in search results. Again, this could be tracked from the demonstrator side, but people/machines querying the triplestore are missed then.

**Comment by ddeboer** [comment]
@faina007 will list the statistics that we would like to have for the Dataset Registry.

**Comment by ddeboer** [comment]
Needed for OCW:

* Het aantal erfgoedinstellingen en datasets dat is opgenomen in het Datasetregister
* Het aantal zoekvragen op het Datasetregister

**Comment by ddeboer** [comment]
> * Het aantal zoekvragen op het Datasetregister

These are done by querying GraphDB, which doesn’t expose metrics, either OpenTelemetry or Prometheus ones. So it seems the only way to monitor this is by exposing query metrics from the demonstrator. Do we consider that a good enough equivalent?

**Comment by EnnoMeijers** [comment]
Ok, that is quite limited indeed. Let's go ahead with this but we should make it very clear that these are metrics coming from the demonstrator/frontend.

**Comment by coret** [comment]
I will be experimenting with the [GraphDB auditlog](https://graphdb.ontotext.com/documentation/10.2/security-auditing.html) on my GraphDB instance to see if this could be a usefull source of statistics.

**Comment by coret** [comment]
> I will be experimenting with the [GraphDB auditlog](https://graphdb.ontotext.com/documentation/10.2/security-auditing.html) on my GraphDB instance to see if this could be a usefull source of statistics.

I have enable the GraphDB audit log as follows

```
docker cp graphdb:/opt/graphdb/conf/graphdb.properties .
# remove the #'s from the following lines in the graphdb.properties file:
# - graphdb.audit.role=ANY
# - graphdb.audit.repository=READ
docker cp graphdb.properties graphdb:/opt/graphdb/conf/
docker container restart graphdb
```

Now, in the graphdb container, audit files (eg. audit-log-2023-06-28.log) are created in the /opt/graphdb/logs directory.

I see lines like:
```
[INFO ] 2023-06-28 17:01:18,337 [http-nio-7200-exec-10 | c.o.f.s.a.AuditLoggingFilter] admin | 10.10.0.32 | 200 | POST http://10.10.0.33:7200/repositories/gtm | -
Request body:
query=select+*+where+%7B+%0A%09%3Fs+%3Fp+%3Fo+.%0A%7D+limit+100+%0A&infer=true&sameAs=true&limit=1001&offset=0
```

**Is this a usefull source for metrics?**

**Comment by ddeboer** [comment]
Metrics are now available at https://statistieken.netwerkdigitaalerfgoed.nl (login required). The only thing missing is the number of queries.

@coret The audit log only seems to add the actual queries (request bodies), which are brittle to parse anyway. The regular stdout log shows:

```
 [INFO ] 2023-07-13 12:08:08,102 [repositories/registry | c.o.g.s.RepositoryController] GET query -1496973462                                                                                                                                      │
│ [INFO ] 2023-07-13 12:08:08,102 [repositories/registry | c.o.g.s.RepositoryController] GET query 762259950                                                                                                                                        │
│ [INFO ] 2023-07-13 12:08:08,104 [repositories/registry | c.o.g.s.TupleQueryResultView] Request for query -1496973462 is finished                                                                                                                  │
│ [INFO ] 2023-07-13 12:08:08,106 [repositories/registry | c.o.g.s.TupleQueryResultView] Request for query 762259950 is finished                                                                                                                    │
│ [INFO ] 2023-07-13 12:08:08,580 [repositories/registry | c.o.g.s.RepositoryController] GET query -1496973462                                                                                                                                      │
│ [INFO ] 2023-07-13 12:08:08,580 [repositories/registry | c.o.g.s.RepositoryController] GET query 762259950                                                                                                                                        │
│ [INFO ] 2023-07-13 12:08:08,582 [repositories/registry | c.o.g.s.TupleQueryResultView] Request for query -1496973462 is finished                                                                                                                  │
│ [INFO ] 2023-07-13 12:08:08,584 [repositories/registry | c.o.g.s.TupleQueryResultView] Request for query 762259950 is finished                                                                                                                    │
│
```
