### ISSUE TITLE
Check compatibility with Triply dataset descriptions

### ISSUE THREAD

**Issue by ddeboer** [netwerk-digitaal-erfgoed/dataset-register#733]
For example

- https://data.netwerkdigitaalerfgoed.nl/Anne-Frank-Stichting/Anne-Frank-Kennisbank: now [valid](https://datasetregister.netwerkdigitaalerfgoed.nl/validate.php?url=https%3A%2F%2Fdata.netwerkdigitaalerfgoed.nl%2FAnne-Frank-Stichting%2FAnne-Frank-Kennisbank)
- https://data.netwerkdigitaalerfgoed.nl/coret/GoudaTimeMachine: [same](https://data.netwerkdigitaalerfgoed.nl/coret/GoudaTimeMachine)

See also https://github.com/netwerk-digitaal-erfgoed/dataset-register/issues/698, #352

**Comment by coret** [comment]
The license is probably missing because the user hasn't defined a license for the dataset (this isn't required within TriplyDB).

I'll ask Triply about their datasetdescription improvement.

**Comment by ddeboer** [comment]
> The license is probably missing because the user hasn't defined a license for the dataset (this isn't required within TriplyDB).

@coret will ask Triply whether license can be a required field.

**Comment by coret** [comment]
Will not be a required field.
