### ISSUE TITLE
Wrong dateRead type (lang)

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/dataset-register#821]
In the process of investigating https://github.com/netwerk-digitaal-erfgoed/dataset-register/issues/817 I exported the https://demo.netwerkdigitaalerfgoed.nl/registry/registrations graph in order to convert the file to readable Turtle. 

Riot exited soon with errors, related to lines like:
```
<....> <http://schema.org/dateRead> "2022-03-14T03:00:43.291Z"^^<xsd:dateTime> .
<....> <http://schema.org/dateRead> "2022-03-15T04:01:01.729Z"@xsd:datetime .
```

Correct syntax being:
```
<....> <http://schema.org/dateRead> "2023-10-22T16:00:20.326Z"^^<http://www.w3.org/2001/XMLSchema#dateTime> .
```

Query to find these 165,106 incorrect triples:
```
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
SELECT * FROM <https://demo.netwerkdigitaalerfgoed.nl/registry/registrations> WHERE {
    ?s ?p ?o .
    FILTER (langMatches( LANG(?o),"xsd:datetime") || datatype(?o) = <xsd:dateTime>)
}
```

**Comment by coret** [comment]
Next thing riot complained about:
```
<http://data.bibliotheken.nl/id/dataset/rise-alba> <http://schema.org/datePosted> <2021-02-02T08:46:49.551Z> .
```
... only 28x with &lt;http://data.bibliotheken.nl/id/dataset/rise-alba&gt; only

**Comment by ddeboer** [comment]
Hmm, the datetime bug was probably introduced with ffe133784ce85c23c9f242c57819fcac2f4bfe26, and later fixed.

If you like, you can go ahead and remove the old data so we end up with fully valid RDF again.

**Comment by coret** [comment]
As we currently only keep 1 `schema:dateRead` and delete old ones, it's easier to just delete these old ones with the wrong type.
```
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX schema: <http://schema.org/>
DELETE {
    ?s schema:dateRead ?o .
} WHERE {
    ?s schema:dateRead ?o .    
    FILTER (LANGMATCHES(LANG(?o),"xsd:datetime") || datatype(?o)=<xsd:dateTime>)
}

Removed 165104 statements. Update took 5.2s, moments ago.
```
