### ISSUE TITLE
Remove request

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/dataset-register#822]
The datasets of the Gouda Tijdmachine have changed, from https://www.goudatijdmachine.nl/data/... to https://www.goudatijdmachine.nl/omeka/...  The old URI's are automatically redirected to the new location, as a consequence the Gouda Tijdmachine datasets are now in the Datasetregister twice! The "/data/" datasets aren't renewed, the "/omeka/" ones are.

All data in the triplestore (registrations / graphs) regarding https://www.goudatijdmachine.nl/data/... can be removed.

**Comment by ddeboer** [comment]
@coret If you want, you can go ahead and do so yourself.

**Comment by coret** [comment]
I manually deleted related graphs and performed the following query:
```
DELETE {
    ?s ?p ?o .
} WHERE {
    ?s ?p ?o .
    FILTER(CONTAINS(STR(?s),"https://www.goudatijdmachine.nl/data"))
}
Removed 11094 statements. Update took 1.1s, moments ago.
```
