### ISSUE TITLE
Data catalog properties validated but not stored

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/dataset-register#827]
The [requirements](https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/#datacatalog-attributes) state required and recommended properties, which are checked via SHACL (eg. `reg:DatacatalogShape`). 
Yet, these properties are not stored in our triplestore (only the URI).

Was this by design? Or should we also cache the datacatalog information (so these can also be displayed on the [catalog page](https://datasetregister.coret.org/catalog.php?lang=nl&uri=https://www.openarchieven.nl/id/foundlinks-catalog) - in dev).

**Comment by ddeboer** [comment]
`schema:includedInDataCatalog` is now being stored (as `dct:isPartOf`).
