### ISSUE TITLE
Validation issue

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/dataset-register#830]
Validation of https://studiezaal.nijmegen.nl/Atlantispubliek/data/set/Catalog results in the error `De URL kan worden gevonden, maar bevat geen datasets.`. 

Butt https://studiezaal.nijmegen.nl/Atlantispubliek/data/set/Catalog.xml (which has the same contents as `curl https://studiezaal.nijmegen.nl/Atlantispubliek/data/set/Catalog`) shows no errors?

What Accept header is the API validate method using to fetch the URL?

**Comment by ddeboer** [comment]
Reported at comunica/comunica#1291.

**Comment by ddeboer** [comment]
Due to bad server configuration, see https://github.com/comunica/comunica/issues/1291#issuecomment-1820906002.

**Comment by coret** [comment]
Has the vendor been informed about the bad server configuration and given instructions how to fix?
