### ISSUE TITLE
Several date types used for dct:issued/dct:modified 

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/dataset-register#846]
Question from @sdevalk turned in to issue (actually, several issues):
> Ik heb een praktische vraag over de triplestore van het Datasetregister. Ik wil de 'dct:modified' van datasets gebruiken om te controleren of en wanneer datasets voor het laatst gewijzigd zijn.
>
> Als ik de volgende vraag stel via https://triplestore.netwerkdigitaalerfgoed.nl/sparql
>
> PREFIX dcat: <http://www.w3.org/ns/dcat#>
> PREFIX dct: <http://purl.org/dc/terms/>
>
> SELECT *
> WHERE {
>  ?dataset a dcat:Dataset ;
>    dct:modified ?dateModified .
> }
>
> ...dan krijg ik allerlei resultaten - mooi! Ik zie evenwel dat het datatype van de 'dct:modified' nogal verschilt. Bijvoorbeeld:
>
> http://schema.org/Date
> https://schema.org/DateTime
> xsd:date
> xsd:dateTime
>
> En er zijn ook datasets waar geen datatype is meegegeven aan de 'dct:modified'.
>
> Ik realiseer me dat de requirements geen uitspraak doen over het datatype dat bronhouders moeten meegeven [1]. Desondanks: als afnemer/gebruiker van het Datasetregister maakt de diversiteit aan datatypes het wel lastig om datasetbeschrijvingen op een uniforme wijze te bevragen. Ik begrijp dat er altijd een zekere verscheidenheid zal zijn - een datum die een 'date' is wil je als 'date' markeren, niet als 'datetime' (en vice versa). Maar datums met een verschil tussen 'http' en 'https' (Schema.org) zijn vervelend, net als datums die de ene keer uit Schema.org komen en de andere keer uit XSD :)
>
> Weet jij van plannen om de datatypes van datums te standaardiseren in de triplestore? Of andersom: wordt er bewust niet op gestandaardiseerd en moeten afnemers - zoals ik - dat in hun queries oplossen?

When you [lookup](https://triplestore.netwerkdigitaalerfgoed.nl/sparql?name=&infer=true&sameAs=true&query=PREFIX%20dct%3A%20%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0APREFIX%20rdf%3A%20%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0ASELECT%20%3Ftype%20(COUNT(%3Ftype)%20AS%20%3Fused)%0AWHERE%20%7B%0A%20%20%20%20%7B%20%3Fd%20dct%3Amodified%20%3Fdate%20.%0A%20%20%20%20%7D%20UNION%20%7B%0A%20%20%20%20%20%20%20%20%3Fd%20dct%3Aissued%20%3Fdate%20%3B%0A%20%20%20%20%7D%0A%20%20%20%20BIND(datatype(%3Fdate)%20AS%20%3Ftype)%0A%7D%20GROUP%20BY%20%3Ftype) the types of `dct:issued` and `dct:modified` properties via 
```
PREFIX dct: <http://purl.org/dc/terms/>
PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
SELECT ?type (COUNT(?type) AS ?used)
WHERE {
    { ?d dct:modified ?date .
    } UNION {
        ?d dct:issued ?date ;
    }
    BIND(datatype(?date) AS ?type)
} GROUP BY ?type
```
you get:

  | type | used
-- | -- | --
1 | http://schema.org/Date | "15446"^^xsd:integer
2 | xsd:date | "77"^^xsd:integer
3 | xsd:string | "36"^^xsd:integer
4 | https://schema.org/DateTime | "384"^^xsd:integer
5 | xsd:dateTime | "10"^^xsd:integer
6 | xml:date | "25"^^xsd:integer
7 | http://schema.org/DateTime | "6"^^xsd:integer

The validation of dataset descriptions via [SHACL](https://github.com/netwerk-digitaal-erfgoed/dataset-register/blob/main/shacl/register.ttl) should have 'eliminated' 3 and 6 but didn't? ***issue**:
```
reg:DateTimeShape a sh:NodeShape ;
    sh:or (
        [ sh:datatype schema:Date ]
        [ sh:datatype schema:DateTime ]
        [ sh:datatype xsd:dateTime ]
        [ sh:datatype xsd:date ]
    ) ;
    sh:name "dateTime" ;
    sh:message "Datum moet van het type schema:Date/xsd:date of schema:DateTime/xsd:dateTime zijn"@nl, "Date must be schema:Date/xsd:date or schema:dateTime/xsd:dateTime"@en ;
    sh:severity sh:Warning ;
.
```

Conversion in the crawler should have `eliminated` 4 (https > http). But wasn't? ***issue**

With our current SHACL we still allow several datatypes. This isn't in the specification. [Section 4.2.3](https://netwerk-digitaal-erfgoed.github.io/requirements-datasets/#dataset-date) even shows `xsd:string` in the example. ***issue**. 

And with multiple allowed datatypes for dates, this make (conversion and) query-ing harder! Maybe, rethink? ***issue**

For handling different date types in a SPARQL query, I've used a **workaround** in our [data story](https://datasetregister.netwerkdigitaalerfgoed.nl/datastory.php) (distributions section). For the query of @sdevalk this would become:
```
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dct: <http://purl.org/dc/terms/>
SELECT ?dataset ?dateModified WHERE {
    ?dataset a dcat:Dataset ;
             dct:modified ?m .
    BIND(SUBSTR(STR(?m),1,10) AS ?dateModified)
}
```

**Comment by ddeboer** [comment]
Unfortunately, that is now how SHACL works. Because all date properties are optional, we have to specify `sh:minCount 0`, which causes invalid dates (such as strings) simply to be ignored instead of being reported.

Anyway, I agree with @sdevalk’s issue, so let me think about a solution.
