### ISSUE TITLE
Publisher available but not converted/stored

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/dataset-register#866]
The following SPARQL query which looks for datasets **without** a publisher shows 4 datasets - this should **not** be possible (as this is a mandatory property):
```
PREFIX dcat: <http://www.w3.org/ns/dcat#>
PREFIX dct:  <http://purl.org/dc/terms/>
SELECT * WHERE {
    ?dataset a dcat:Dataset .
    FILTER NOT EXISTS {
        ?dataset dct:publisher ?publisher .
    }
}
```

One of the datasets is [https://doi.org/10.5281/zenodo.6949127](https://datasetregister.netwerkdigitaalerfgoed.nl/show.php?lang=nl&uri=https://doi.org/10.5281/zenodo.6949127) - this link shows that the dataset is included in the Dataset Register, so it is valid according to our SHACL validation - and this is based on https://gitlab.com/uvacreate/amsterdam-time-machine/infrastructure-pilot/-/raw/main/datasets/huurwaarden1832.jsonld which includes:
```
publisher: {
  @type: "Organization",
  @id: "https://www.amsterdamtimemachine.nl/",
  name: "Amsterdam Time Machine"
},
```

**Comment by ddeboer** [comment]
As [you can see in the SHACL](https://github.com/netwerk-digitaal-erfgoed/dataset-register/blob/92915d8a0923674fed5770392cb3c4df62f23470/shacl/register.ttl#L283), the severity for publisher is warning, not violation, so this is possible.

**Comment by coret** [comment]
But the issue is that the publisher data isn't stored in the triplestore. Why is this?
