### ISSUE TITLE
Time-out on NA datacatalog

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/dataset-register#931]
The NA has updated their hydra-paged catalog https://archief.nl/id/datacatalog/toegang (added OAI-PMH distributions), but these changes don't end up in the triplestore of the Dataset Register.

Registering https://archief.nl/id/datacatalog/toegang via the Dataset Register API shows a time-out error (which I think isn't caused by NA infrastructure, but by the handling of the large quantity of dataset descriptions):
```
curl 'https://datasetregister.netwerkdigitaalerfgoed.nl/api/datasets' \
            -H 'link: <http://www.w3.org/ns/ldp#RDFSource>; rel="type",<http://www.w3.org/ns/ldp#Resource>; rel="type"' \
            -H 'content-type: application/ld+json' \
            --data-binary '{"@id":"https://archief.nl/id/datacatalog/toegang"}'
<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by ddeboer** [comment]
Fixed. The datasets now have an OAI-PMH distribution; see for example https://datasetregister.netwerkdigitaalerfgoed.nl/show.php?lang=en&uri=https://archief.nl/id/dataset/toegang/2.04.101.
