### ISSUE TITLE
Swagger not shown

### ISSUE THREAD

**Issue by coret** [netwerk-digitaal-erfgoed/dataset-register#962]
The OpenAPI documentation about the Dataset Register API via https://datasetregister.netwerkdigitaalerfgoed.nl/api/static/index.html is not shown. The necessary static files seem to be missing:

![image](https://github.com/user-attachments/assets/7cbc1cdf-5e83-4465-b5ae-8eb9fd627390)

**Comment by ddeboer** [comment]
We have a test that the docs work, but that only verifies a 200 status, which still passed. Docs fixed in #961. Thanks for reporting!

**Comment by EnnoMeijers** [comment]
Just for my curiosity: I expected https://datasetregister.netwerkdigitaalerfgoed.nl/api/static/index.html to lead to the documentation but it returns the home page. Am I missing something here?

**Comment by coret** [comment]
The current address seems to be https://datasetregister.netwerkdigitaalerfgoed.nl/api/
(I'll update the link on https://datasetregister.netwerkdigitaalerfgoed.nl/apidoc.php)

**Comment by ddeboer** [comment]
That’s right @coret, thanks!
